global using NPOI.XSSF.UserModel;
global using NUnit.Framework;
global using static ExcelUtileTest.Utilities.TimeCount;
global using ExcelUtileTest.Mocks;
global using ExcelUtileTest.Utilities;
global using ExcelUtileTest.Entities;
global using System.Diagnostics;
global using ExcelUtile.ExcelCore;
global using ExcelUtile.Formats;
global using ExcelUtile;
global using NPOI.SS.UserModel;