name: test action write by myself
on: push
jobs:
    changedfile:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: get changed directories
              id: changefile
              uses: mingrenliu/TSGithubAction@v1.3
              with:
                directories: "ConfigurationCenter;ExcelUtils;dns;DatabaseHandler;Analyzers/ControllerAnalyzer;Analyzers/InheritGenerator;Analyzers/ServiceAnalyzer"
                token: "${{github.token}}"
                ignore: "**.md"
            - name: display changed directories
              run:
                echo ${{steps.changefile.outputs}}

